[tool.autopep8]
max_line_length = 120
ignore = ["E203", "E701", "W503"]
exclude = [".git", "__pycache__", "docs", "old", "build", "dist", ".venv", "cache"]
aggressive = 1

[tool.pycodestyle]
max_line_length = 120
ignore = ["E203", "E701", "W503"]
exclude = [".git", "__pycache__", "docs", "old", "build", "dist", ".venv", "cache"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38'] 